#include "test_utils.h"
#include "sphere.h"
#include "cube.h"
#include "mesh.h"
#include "vec3.h"

/******************************************************************************
 * Unit tests for mesh generation.
 *
 * The following functions are tested:
 *
 *     - load_cube()
 *     - load_sphere()
 *     - remove_duplicate_vertices() indirectly through load_cube()
 *
 * The tests verify:
 *
 *     - mesh generation succeeds;
 *     - expected numbers of vertices and triangles are produced;
 *     - cube vertices are located in the expected domain;
 *     - duplicate vertices are removed;
 *     - sphere vertices are normalized.
 *****************************************************************************/

/******************************************************************************
 * Check that all vertex positions are unique.
 *
 * This is a simple O(N^2) implementation intended only for small unit tests.
 *****************************************************************************/
static bool has_no_duplicate_vertices(const Mesh &m) {
    size_t count = m.vertex_count();

    for (size_t i = 0; i < count; ++i) {
        for (size_t j = i + 1; j < count; ++j) {
            if (m.positions[i] == m.positions[j]) {
                return false;
            }
        }
    }

    return true;
}

/******************************************************************************
 * Test cube generation.
 *
 * For subdiv = 1:
 *
 *     - The initial cube contains 6 faces with 4 vertices each.
 *     - remove_duplicate_vertices() merges vertices shared by several faces.
 *     - The final cube therefore contains 8 unique vertices.
 *
 * Each face contains 2 triangles:
 *
 *     6 faces * 2 triangles = 12 triangles
 *****************************************************************************/
static void test_cube() {
    Mesh mesh;

    int res = load_cube(mesh, 1);

    check(res == 0,
          "load_cube(subdiv=1) succeeds");

    check(mesh.vertex_count() == 8,
          "Cube with subdiv=1 has 8 unique vertices");

    check(mesh.triangle_count() == 12,
          "Cube with subdiv=1 has 12 triangles");

    check(has_no_duplicate_vertices(mesh),
          "Cube contains no duplicate vertices");

    /*
     * The generated cube is defined in the domain:
     *
     *     [-1, 1] x [-1, 1] x [-1, 1]
     */
    bool valid_positions = true;

    for (size_t i = 0; i < mesh.vertex_count(); ++i) {
        const Vec3 &p = mesh.positions[i];

        if (p[0] < -1.0 || p[0] > 1.0 ||
            p[1] < -1.0 || p[1] > 1.0 ||
            p[2] < -1.0 || p[2] > 1.0) {
            valid_positions = false;
            break;
        }
    }

    check(valid_positions,
          "Cube vertices are inside [-1,1]^3");
}

/******************************************************************************
 * Test invalid subdivision values.
 *****************************************************************************/
static void test_cube_invalid_subdiv() {
    Mesh mesh;

    int res = load_cube(mesh, 0);

    check(res == -1,
          "load_cube(subdiv=0) returns an error");
}

/******************************************************************************
 * Test sphere generation.
 *
 * The sphere is generated by:
 *
 *     1. generating a cube;
 *     2. removing duplicate vertices;
 *     3. projecting every vertex onto the unit sphere.
 *
 * Therefore, every vertex must satisfy:
 *
 *     ||p|| = 1
 *****************************************************************************/
static void test_sphere() {
    Mesh mesh;

    int res = load_sphere(mesh, 1);

    check(res == 0,
          "load_sphere(subdiv=1) succeeds");

    check(mesh.vertex_count() == 8,
          "Sphere with subdiv=1 has 8 vertices");

    check(mesh.triangle_count() == 12,
          "Sphere with subdiv=1 has 12 triangles");

    bool normalized_ok = true;

    for (size_t i = 0; i < mesh.vertex_count(); ++i) {
        const Vec3 &p = mesh.positions[i];

        /* Cast components to double before squaring to avoid accumulating
         * float rounding error in the sum. */
        double x = (double)p[0];
        double y = (double)p[1];
        double z = (double)p[2];

        double norm = std::sqrt(x * x + y * y + z * z);

        /* Tolerance adapted to single-precision (float) vertex storage */
        if (!almost_equal(norm, 1.0, 1e-5)) {
            normalized_ok = false;
            break;
        }
    }

    check(normalized_ok,
          "All sphere vertices have unit norm");
}

int main() {
    LOG_MSG("Mesh generation unit tests");

    test_cube();
    test_cube_invalid_subdiv();
    test_sphere();

    if (!g_all_passed) {
        LOG_MSG("TEST FAILED");
        return 1;
    }

    LOG_MSG("TEST PASSED");
    return 0;
}