#pragma once

#include "mesh.h"

/******************************************************************************
 * Cube mesh generation.
 *
 * The cube is generated by subdividing each of its six faces into a regular
 * grid of quadrilateral cells. Each cell is then split into two triangles.
 *
 * The six faces are initially generated independently, which means that
 * vertices lying on shared edges and corners are duplicated.
 *
 * remove_duplicate_vertices() is called at the end of the generation process
 * to merge identical vertices and update the triangle indices accordingly.
 *****************************************************************************/

/******************************************************************************
 * Generate a triangulated cube mesh.
 *
 * @param m
 *     Output mesh.
 *
 * @param subdiv
 *     Number of subdivisions along each edge of a cube face.
 *
 *     Each face contains:
 *
 *         subdiv * subdiv
 *
 *     quadrilateral cells, each split into two triangles.
 *
 * @return
 *     0 on success.
 *    -1 if the requested subdivision count is invalid.
 *****************************************************************************/
int load_cube(Mesh & m, size_t subdiv);


/******************************************************************************
 * Generate a cube mesh using a nested dissection ordering.
 *
 * This function is intended to generate the same type of cube geometry while
 * applying a vertex or element ordering suitable for algorithms that benefit
 * from nested dissection.
 *****************************************************************************/
int load_cube_nested_dissect(Mesh & m, size_t subdiv);