name: PLNS-SOLVER CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master


jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev xorg-dev \
                                    libwayland-dev wayland-protocols \
                                    libxkbcommon-dev xvfb mesa-utils

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build --parallel

      - name: Run tests
        run: xvfb-run --auto-servernum ctest --test-dir build --output-on-failure